version: '3.5'
services:
  wordpress:
    container_name: wordpressContainer
    image: wordpress
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: sa
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html
  db:
    container_name: mysqlContainer
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: