version: '3.5'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wp-db
    volumes:
      - wordpress:/var/www
  wp-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql


volumes:
  wordpress:
  db:
